### ISSUE TITLE
Enhancement Request: Use requirements.txt for Dependency Specification

### ISSUE THREAD

**Issue by KagemaNjoroge** [Thutazaw09/Point-Of-Sale-System#1]
## Request
While reviewing the project's README, I noticed that dependencies are outlined for installation. To enhance the project's structure and align with best practices, could we consider transitioning to a `requirements.txt` file for specifying and managing dependencies?

## Rationale
Using a `requirements.txt` file provides several advantages:
1. **Consistency:** It ensures a standardized approach to dependency specification, making it easier for contributors and users to understand and replicate the environment.
   
2. **Ease of Maintenance:** Managing dependencies in a dedicated file simplifies updates and tracking of changes, promoting a more organized and maintainable project structure.

3. **Reproducibility:** A `requirements.txt` file facilitates consistent environment replication, reducing the likelihood of compatibility issues and streamlining collaboration.

## Proposed Action
1. **Create a `requirements.txt` file:** Move the current dependency specifications from the README to a dedicated `requirements.txt` file in the project's root directory.

2. **Update README:** Provide instructions in the README for users and contributors to install dependencies using the new `requirements.txt` file.

This enhancement would not only align with best practices but also make the project more accessible and maintainable. Thank you for considering this suggestion!

**Comment by Thutazaw09** [comment]
Dear KagemaNjoroge,

I extend my sincere gratitude for your invaluable contributions to the POS (Point of Sale) system. Your efforts have not gone unnoticed, and I am genuinely appreciative of the positive impact they have had.

Upon careful consideration of your Proposed Action, I am inclined to proceed with the outlined steps. Your insights and recommendations are highly regarded, and I trust that they will contribute significantly to the success of our endeavors.

Thank you once again for your dedication and expertise. I look forward to the positive outcomes that will undoubtedly result from your valuable contributions.

Best regards,
Thu Ta Zaw
